org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# TrialsExpanded
modId=trialsexpanded
modName=Trials Expanded
modLicense=MIT
modVersion=1.0.0
modGroupId=dev.jaronline.trialsexpanded
modAuthors=Jaronline
modCredits=Lieke60
modDescription=A mod that allows trial vaults and spawners to be mined and crafted
modJavaVersion=21

# Minecraft
minecraftVersion=1.21.1
minecraftVersionRange=[1.21.1]
minecraftVersionRangeStart=1.21.1

# NeoForge
neoVersion=21.1.219
neoVersionRange=[21.1.219,21.2)
loaderVersionRange=[1,)

# Mappings
# https://parchmentmc.org/docs/getting-started
parchmentMinecraftVersion=1.21.1
parchmentMappingsVersion=2024.11.17

# Publishing
curseProjectId=1455411
modrinthId=xgx3NV2j

# Mod Dev Dependencies
jeiVersion=19.27.0.340
## Testing
jUnitVersion=5.14.2
