@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.jaronline.trialsexpanded;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
